class MangroveDatumSerializer < ActiveModel::Serializer
  attributes :id,
    :date,
    :gain_m2,
    :loss_m2,
    :net_change_m2,
    :length_m,
    :area_m2,
    :hmax_m,
    :agb_mgha_1,
    :hba_m,
    :con_hotspot_summary_km2,
    :agb_hist_mgha_1,
    :hba_hist_m,
    :hmax_hist_m,
    :agb_tco2e,
    :bgb_tco2e,
    :soc_tco2e,
    :toc_tco2e,
    :toc_hist_tco2eha
end
